<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AttributesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('attributes')->delete();
        
        \DB::table('attributes')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'sku',
                'admin_name' => 'SKU',
                'type' => 'text',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 1,
                'is_required' => 1,
                'is_unique' => 1,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'name',
                'admin_name' => 'Name',
                'type' => 'text',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 3,
                'is_required' => 1,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 1,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 1,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'url_key',
                'admin_name' => 'URL Key',
                'type' => 'text',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 4,
                'is_required' => 1,
                'is_unique' => 1,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 1,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'tax_category_id',
                'admin_name' => 'Tax Category',
                'type' => 'select',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 5,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 1,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'new',
                'admin_name' => 'New',
                'type' => 'boolean',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 6,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => 1,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'featured',
                'admin_name' => 'Featured',
                'type' => 'boolean',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 7,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => 1,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'visible_individually',
                'admin_name' => 'Visible Individually',
                'type' => 'boolean',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 9,
                'is_required' => 1,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => 1,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'status',
                'admin_name' => 'Status',
                'type' => 'boolean',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 10,
                'is_required' => 1,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 1,
                'default_value' => 1,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'short_description',
                'admin_name' => 'Short Description',
                'type' => 'textarea',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 11,
                'is_required' => 1,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 1,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 1,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'description',
                'admin_name' => 'Description',
                'type' => 'textarea',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 12,
                'is_required' => 1,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 1,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 1,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 1,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 'price',
                'admin_name' => 'Price',
                'type' => 'price',
                'swatch_type' => NULL,
                'validation' => 'decimal',
                'regex' => NULL,
                'position' => 13,
                'is_required' => 1,
                'is_unique' => 0,
                'is_filterable' => 1,
                'is_comparable' => 1,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'cost',
                'admin_name' => 'Cost',
                'type' => 'price',
                'swatch_type' => NULL,
                'validation' => 'decimal',
                'regex' => NULL,
                'position' => 14,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 1,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            12 => 
            array (
                'id' => 13,
                'code' => 'special_price',
                'admin_name' => 'Special Price',
                'type' => 'price',
                'swatch_type' => NULL,
                'validation' => 'decimal',
                'regex' => NULL,
                'position' => 15,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 'special_price_from',
                'admin_name' => 'Special Price From',
                'type' => 'date',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 16,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 1,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            14 => 
            array (
                'id' => 15,
                'code' => 'special_price_to',
                'admin_name' => 'Special Price To',
                'type' => 'date',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 17,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 1,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            15 => 
            array (
                'id' => 16,
                'code' => 'meta_title',
                'admin_name' => 'Meta Title',
                'type' => 'textarea',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 18,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 1,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            16 => 
            array (
                'id' => 17,
                'code' => 'meta_keywords',
                'admin_name' => 'Meta Keywords',
                'type' => 'textarea',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 20,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 1,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            17 => 
            array (
                'id' => 18,
                'code' => 'meta_description',
                'admin_name' => 'Meta Description',
                'type' => 'textarea',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 21,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 1,
                'is_visible_on_front' => 0,
                'value_per_locale' => 1,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            18 => 
            array (
                'id' => 19,
                'code' => 'length',
                'admin_name' => 'Length',
                'type' => 'text',
                'swatch_type' => NULL,
                'validation' => 'decimal',
                'regex' => NULL,
                'position' => 22,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 1,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            19 => 
            array (
                'id' => 20,
                'code' => 'width',
                'admin_name' => 'Width',
                'type' => 'text',
                'swatch_type' => NULL,
                'validation' => 'decimal',
                'regex' => NULL,
                'position' => 23,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 1,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            20 => 
            array (
                'id' => 21,
                'code' => 'height',
                'admin_name' => 'Height',
                'type' => 'text',
                'swatch_type' => NULL,
                'validation' => 'decimal',
                'regex' => NULL,
                'position' => 24,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 1,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            21 => 
            array (
                'id' => 22,
                'code' => 'weight',
                'admin_name' => 'Weight',
                'type' => 'text',
                'swatch_type' => NULL,
                'validation' => 'decimal',
                'regex' => NULL,
                'position' => 25,
                'is_required' => 1,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            22 => 
            array (
                'id' => 23,
                'code' => 'color',
                'admin_name' => 'Color',
                'type' => 'select',
                'swatch_type' => 'color',
                'validation' => NULL,
                'regex' => NULL,
                'position' => 26,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 1,
                'is_comparable' => 0,
                'is_configurable' => 1,
                'is_user_defined' => 1,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-28 09:22:40',
            ),
            23 => 
            array (
                'id' => 24,
                'code' => 'size',
                'admin_name' => 'Size',
                'type' => 'select',
                'swatch_type' => 'text',
                'validation' => NULL,
                'regex' => NULL,
                'position' => 27,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 1,
                'is_comparable' => 0,
                'is_configurable' => 1,
                'is_user_defined' => 1,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-28 09:22:29',
            ),
            24 => 
            array (
                'id' => 25,
                'code' => 'brand',
                'admin_name' => 'Brand',
                'type' => 'select',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 28,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 1,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 1,
                'is_visible_on_front' => 1,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            25 => 
            array (
                'id' => 26,
                'code' => 'guest_checkout',
                'admin_name' => 'Guest Checkout',
                'type' => 'boolean',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 8,
                'is_required' => 1,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => 1,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            26 => 
            array (
                'id' => 27,
                'code' => 'product_number',
                'admin_name' => 'Product Number',
                'type' => 'text',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 2,
                'is_required' => 0,
                'is_unique' => 1,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            27 => 
            array (
                'id' => 28,
                'code' => 'manage_stock',
                'admin_name' => 'Manage Stock',
                'type' => 'boolean',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => NULL,
                'position' => 1,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 0,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 1,
                'default_value' => 1,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-24 23:09:33',
                'updated_at' => '2025-11-24 23:09:33',
            ),
            28 => 
            array (
                'id' => 29,
                'code' => 'is_special_layout',
                'admin_name' => 'Gunakan Layout Spesial?',
                'type' => 'select',
                'swatch_type' => 'color',
                'validation' => NULL,
                'regex' => '',
                'position' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 1,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-26 17:29:33',
                'updated_at' => '2025-11-26 17:32:59',
            ),
            29 => 
            array (
                'id' => 30,
                'code' => 'special_promo_banner',
                'admin_name' => 'Gambar Banner Promo',
                'type' => 'image',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => '',
                'position' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 1,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-26 17:30:07',
                'updated_at' => '2025-11-26 17:33:11',
            ),
            30 => 
            array (
                'id' => 31,
                'code' => 'special_promo_title',
                'admin_name' => 'Judul Promo',
                'type' => 'text',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => '',
                'position' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 1,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-26 17:30:34',
                'updated_at' => '2025-11-26 17:33:35',
            ),
            31 => 
            array (
                'id' => 32,
                'code' => 'special_countdown_end',
                'admin_name' => 'Tanggal Berakhir Promo',
                'type' => 'datetime',
                'swatch_type' => NULL,
                'validation' => NULL,
                'regex' => '',
                'position' => NULL,
                'is_required' => 0,
                'is_unique' => 0,
                'is_filterable' => 0,
                'is_comparable' => 0,
                'is_configurable' => 0,
                'is_user_defined' => 1,
                'is_visible_on_front' => 0,
                'value_per_locale' => 0,
                'value_per_channel' => 0,
                'default_value' => NULL,
                'enable_wysiwyg' => 0,
                'created_at' => '2025-11-26 17:30:54',
                'updated_at' => '2025-11-26 17:33:51',
            ),
        ));
        
        
    }
}