<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductFlatTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_flat')->delete();
        
        \DB::table('product_flat')->insert(array (
            0 => 
            array (
                'id' => 52,
                'sku' => 'padel-skirt-01',
                'type' => 'configurable',
                'product_number' => '',
                'name' => 'Padel Skirt',
                'short_description' => '<p>Rok padel berwarna putih dengan aksen garis merah, hitam, dan putih di bagian hem. Dibuat dari bahan ringan dan elastis yang mendukung gerakan dinamis di lapangan.</p>',
                'description' => '<p>Rok padel ini menghadirkan tampilan sporty yang elegan melalui desain putih bersih yang dipadukan dengan detail garis merah, hitam, dan putih di bagian bawah. Potongan A-line memberikan siluet rapi sekaligus ruang gerak optimal saat berlari, melompat, atau melakukan rotasi tubuh. Terbuat dari material yang ringan, elastis, dan nyaman dipakai sepanjang permainan. Dilengkapi belt loop untuk menambah fleksibilitas styling. Ideal untuk pemain yang menginginkan performa dan estetika dalam satu tampilan.</p>',
                'url_key' => 'padel-skirt',
                'new' => 1,
                'featured' => 1,
                'status' => 1,
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'price' => NULL,
                'special_price' => NULL,
                'special_price_from' => NULL,
                'special_price_to' => NULL,
                'weight' => NULL,
                'created_at' => '2025-12-03 15:07:55',
                'locale' => 'en',
                'channel' => 'default',
                'attribute_family_id' => 1,
                'product_id' => 52,
                'updated_at' => '2025-12-03 15:26:09',
                'parent_id' => NULL,
                'visible_individually' => 1,
            ),
            1 => 
            array (
                'id' => 53,
                'sku' => 'padel-skirt-01-red',
                'type' => 'simple',
                'product_number' => '2',
                'name' => 'Padel Skirt Red',
                'short_description' => '<p>Rok padel berwarna merah dengan aksen garis  hitam, dan putih di bagian hem. Dibuat dari bahan ringan dan elastis yang mendukung gerakan dinamis di lapangan.</p>',
                'description' => '<p>Rok padel ini menghadirkan tampilan sporty yang elegan melalui desain putih bersih yang dipadukan dengan detail garis merah, hitam, dan putih di bagian bawah. Potongan A-line memberikan siluet rapi sekaligus ruang gerak optimal saat berlari, melompat, atau melakukan rotasi tubuh. Terbuat dari material yang ringan, elastis, dan nyaman dipakai sepanjang permainan. Dilengkapi belt loop untuk menambah fleksibilitas styling. Ideal untuk pemain yang menginginkan performa dan estetika dalam satu tampilan.</p>',
                'url_key' => 'padel-skirt-red',
                'new' => 1,
                'featured' => 1,
                'status' => 1,
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'price' => '150000.0000',
                'special_price' => NULL,
                'special_price_from' => NULL,
                'special_price_to' => NULL,
                'weight' => '250.0000',
                'created_at' => '2025-12-03 15:07:55',
                'locale' => 'en',
                'channel' => 'default',
                'attribute_family_id' => 1,
                'product_id' => 53,
                'updated_at' => '2025-12-03 15:26:09',
                'parent_id' => NULL,
                'visible_individually' => 1,
            ),
            2 => 
            array (
                'id' => 54,
                'sku' => 'padel-skirt-01-whire',
                'type' => 'simple',
                'product_number' => '',
                'name' => 'Padel Skirt White',
                'short_description' => '<p>Rok padel berwarna putih dengan aksen garis merah, hitam, dan putih di bagian hem. Dibuat dari bahan ringan dan elastis yang mendukung gerakan dinamis di lapangan.</p>',
                'description' => '<p>Rok padel ini menghadirkan tampilan sporty yang elegan melalui desain putih bersih yang dipadukan dengan detail garis merah, hitam, dan putih di bagian bawah. Potongan A-line memberikan siluet rapi sekaligus ruang gerak optimal saat berlari, melompat, atau melakukan rotasi tubuh. Terbuat dari material yang ringan, elastis, dan nyaman dipakai sepanjang permainan. Dilengkapi belt loop untuk menambah fleksibilitas styling. Ideal untuk pemain yang menginginkan performa dan estetika dalam satu tampilan.</p>',
                'url_key' => 'padel-skirt-white',
                'new' => 1,
                'featured' => 1,
                'status' => 1,
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'price' => '150000.0000',
                'special_price' => NULL,
                'special_price_from' => NULL,
                'special_price_to' => NULL,
                'weight' => '250.0000',
                'created_at' => '2025-12-03 15:07:55',
                'locale' => 'en',
                'channel' => 'default',
                'attribute_family_id' => 1,
                'product_id' => 54,
                'updated_at' => '2025-12-03 15:26:09',
                'parent_id' => NULL,
                'visible_individually' => 1,
            ),
            3 => 
            array (
                'id' => 55,
                'sku' => 'padel-skirt-01-red-m',
                'type' => 'simple',
                'product_number' => '',
                'name' => 'Padel Skirt Red',
                'short_description' => '<p>Rok padel berwarna  merah dengan aksen garis hitam, dan putih di bagian hem. Dibuat dari bahan ringan dan elastis yang mendukung gerakan dinamis di lapangan.</p>',
                'description' => '<p>Rok padel ini menghadirkan tampilan sporty yang elegan melalui desain putih bersih yang dipadukan dengan detail garis merah, hitam, dan putih di bagian bawah. Potongan A-line memberikan siluet rapi sekaligus ruang gerak optimal saat berlari, melompat, atau melakukan rotasi tubuh. Terbuat dari material yang ringan, elastis, dan nyaman dipakai sepanjang permainan. Dilengkapi belt loop untuk menambah fleksibilitas styling. Ideal untuk pemain yang menginginkan performa dan estetika dalam satu tampilan.</p>',
                'url_key' => 'padel-skirt-red-m',
                'new' => 1,
                'featured' => 1,
                'status' => 1,
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'price' => '150000.0000',
                'special_price' => NULL,
                'special_price_from' => NULL,
                'special_price_to' => NULL,
                'weight' => '250.0000',
                'created_at' => '2025-12-03 15:07:55',
                'locale' => 'en',
                'channel' => 'default',
                'attribute_family_id' => 1,
                'product_id' => 55,
                'updated_at' => '2025-12-03 15:26:09',
                'parent_id' => NULL,
                'visible_individually' => 1,
            ),
            4 => 
            array (
                'id' => 56,
                'sku' => 'padel-skirt-01-white-m',
                'type' => 'simple',
                'product_number' => '',
                'name' => 'Padel Skirt White',
                'short_description' => '<p>Rok padel berwarna putih dengan aksen garis merah, hitam, dan putih di bagian hem. Dibuat dari bahan ringan dan elastis yang mendukung gerakan dinamis di lapangan.</p>',
                'description' => '<p>Rok padel ini menghadirkan tampilan sporty yang elegan melalui desain putih bersih yang dipadukan dengan detail garis merah, hitam, dan putih di bagian bawah. Potongan A-line memberikan siluet rapi sekaligus ruang gerak optimal saat berlari, melompat, atau melakukan rotasi tubuh. Terbuat dari material yang ringan, elastis, dan nyaman dipakai sepanjang permainan. Dilengkapi belt loop untuk menambah fleksibilitas styling. Ideal untuk pemain yang menginginkan performa dan estetika dalam satu tampilan.</p>',
                'url_key' => 'padel-skirt-white-m',
                'new' => 1,
                'featured' => 1,
                'status' => 1,
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'price' => '150000.0000',
                'special_price' => NULL,
                'special_price_from' => NULL,
                'special_price_to' => NULL,
                'weight' => '250.0000',
                'created_at' => '2025-12-03 15:07:55',
                'locale' => 'en',
                'channel' => 'default',
                'attribute_family_id' => 1,
                'product_id' => 56,
                'updated_at' => '2025-12-03 15:26:09',
                'parent_id' => NULL,
                'visible_individually' => 1,
            ),
            5 => 
            array (
                'id' => 57,
                'sku' => 'padel-top-01',
                'type' => 'configurable',
                'product_number' => '',
                'name' => 'Padel Top',
                'short_description' => '<p>Atasan padel tanpa lengan dengan kombinasi warna putih, hitam, dan merah. Didesain dengan kerah polo kontras, bukaan kancing depan, serta logo 3ON pada dada, memberikan tampilan sporty dan modern di lapangan.</p>',
                'description' => '<p>Atasan padel ini menggabungkan nuansa sporty dan elegan melalui desain polo tanpa lengan yang bersih dan proporsional. Warna dasar putih dipertegas dengan aksen hitam-merah pada kerah, placket kancing, dan tepi lengan, menciptakan tampilan yang tegas namun tetap minimalis.</p>
<p>Terbuat dari bahan performa yang ringan dan breathable, atasan ini membantu menjaga kenyamanan saat bergerak intens di lapangan. Siluetnya mengikuti bentuk tubuh tanpa membatasi ruang gerak, sementara kerah polo memberikan sentuhan rapi yang cocok untuk gaya kompetitif maupun latihan santai. Logo 3ON yang terpasang pada bagian dada menambah karakter sekaligus identitas visual yang kuat.</p>',
                'url_key' => 'padel-top-01',
                'new' => 1,
                'featured' => 1,
                'status' => 1,
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'price' => NULL,
                'special_price' => NULL,
                'special_price_from' => NULL,
                'special_price_to' => NULL,
                'weight' => NULL,
                'created_at' => '2025-12-03 15:28:50',
                'locale' => 'en',
                'channel' => 'default',
                'attribute_family_id' => 1,
                'product_id' => 57,
                'updated_at' => '2025-12-03 15:36:08',
                'parent_id' => NULL,
                'visible_individually' => 1,
            ),
            6 => 
            array (
                'id' => 58,
                'sku' => 'padel-top-01-red-s',
                'type' => 'simple',
                'product_number' => '',
                'name' => 'Padel Top Red',
                'short_description' => '<p>Atasan padel tanpa lengan dengan kombinasi  hitam dan merah. Didesain dengan kerah polo kontras, bukaan kancing depan, serta logo 3ON pada dada, memberikan tampilan sporty dan modern di lapangan.</p>',
                'description' => '<p>Atasan padel ini menggabungkan nuansa sporty dan elegan melalui desain polo tanpa lengan yang bersih dan proporsional. Warna dasar merah dipertegas dengan aksen hitam-merah pada kerah, placket kancing, dan tepi lengan, menciptakan tampilan yang tegas namun tetap minimalis.</p>
<p>Terbuat dari bahan performa yang ringan dan breathable, atasan ini membantu menjaga kenyamanan saat bergerak intens di lapangan. Siluetnya mengikuti bentuk tubuh tanpa membatasi ruang gerak, sementara kerah polo memberikan sentuhan rapi yang cocok untuk gaya kompetitif maupun latihan santai. Logo 3ON yang terpasang pada bagian dada menambah karakter sekaligus identitas visual yang kuat.</p>',
                'url_key' => 'padel-top-red-s',
                'new' => 1,
                'featured' => 1,
                'status' => 1,
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'price' => '150000.0000',
                'special_price' => NULL,
                'special_price_from' => NULL,
                'special_price_to' => NULL,
                'weight' => '250.0000',
                'created_at' => '2025-12-03 15:28:50',
                'locale' => 'en',
                'channel' => 'default',
                'attribute_family_id' => 1,
                'product_id' => 58,
                'updated_at' => '2025-12-03 16:13:38',
                'parent_id' => NULL,
                'visible_individually' => 1,
            ),
            7 => 
            array (
                'id' => 59,
                'sku' => 'padel-top-01-white-s',
                'type' => 'simple',
                'product_number' => '',
                'name' => 'Padel Top White',
                'short_description' => '<p>Atasan padel tanpa lengan dengan kombinasi warna putih, hitam, dan merah. Didesain dengan kerah polo kontras, bukaan kancing depan, serta logo 3ON pada dada, memberikan tampilan sporty dan modern di lapangan.</p>',
                'description' => '<p>Atasan padel ini menggabungkan nuansa sporty dan elegan melalui desain polo tanpa lengan yang bersih dan proporsional. Warna dasar putih dipertegas dengan aksen hitam-merah pada kerah, placket kancing, dan tepi lengan, menciptakan tampilan yang tegas namun tetap minimalis.</p>
<p>Terbuat dari bahan performa yang ringan dan breathable, atasan ini membantu menjaga kenyamanan saat bergerak intens di lapangan. Siluetnya mengikuti bentuk tubuh tanpa membatasi ruang gerak, sementara kerah polo memberikan sentuhan rapi yang cocok untuk gaya kompetitif maupun latihan santai. Logo 3ON yang terpasang pada bagian dada menambah karakter sekaligus identitas visual yang kuat.</p>',
                'url_key' => 'padel-top-white',
                'new' => 1,
                'featured' => 1,
                'status' => 1,
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'price' => '150000.0000',
                'special_price' => NULL,
                'special_price_from' => NULL,
                'special_price_to' => NULL,
                'weight' => '250.0000',
                'created_at' => '2025-12-03 15:28:50',
                'locale' => 'en',
                'channel' => 'default',
                'attribute_family_id' => 1,
                'product_id' => 59,
                'updated_at' => '2025-12-03 16:13:50',
                'parent_id' => NULL,
                'visible_individually' => 1,
            ),
            8 => 
            array (
                'id' => 62,
                'sku' => 'padel-hat',
                'type' => 'configurable',
                'product_number' => '',
                'name' => 'Padel Hat',
                'short_description' => '<p>Visor padel berwarna putih dengan logo 3ON pada bagian depan. Ringan, nyaman, dan dirancang untuk melindungi wajah dari sinar matahari tanpa menghalangi sirkulasi udara.</p>',
                'description' => '<p>Visor padel ini menghadirkan tampilan bersih dan modern melalui desain putih solid yang dipadukan dengan logo 3ON pada bagian depan. Bentuk brim yang lebar memberikan perlindungan optimal dari sinar matahari, membantu menjaga fokus selama permainan tanpa mengganggu pandangan.</p>
<p>Terbuat dari material ringan yang mudah menyerap keringat, visor ini menjaga kenyamanan di bawah terik matahari sekaligus memungkinkan aliran udara tetap maksimal karena tidak menutup bagian atas kepala. Strap belakang biasanya dapat disesuaikan, sehingga pas untuk berbagai ukuran kepala dan tetap stabil meski digunakan saat bergerak cepat di lapangan.</p>',
                'url_key' => 'padel-hat',
                'new' => 1,
                'featured' => 1,
                'status' => 1,
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'price' => NULL,
                'special_price' => NULL,
                'special_price_from' => NULL,
                'special_price_to' => NULL,
                'weight' => NULL,
                'created_at' => '2025-12-03 15:48:12',
                'locale' => 'en',
                'channel' => 'default',
                'attribute_family_id' => 1,
                'product_id' => 62,
                'updated_at' => '2025-12-03 15:51:42',
                'parent_id' => NULL,
                'visible_individually' => 1,
            ),
            9 => 
            array (
                'id' => 63,
                'sku' => 'padel-hat-01-red',
                'type' => 'simple',
                'product_number' => '',
                'name' => 'Padel Hat Red',
                'short_description' => '<p>Visor padel berwarna merah dengan logo 3ON pada bagian depan. Ringan, nyaman, dan dirancang untuk melindungi wajah dari sinar matahari tanpa menghalangi sirkulasi udara.</p>',
                'description' => '<p>Visor padel ini menghadirkan tampilan bersih dan modern melalui desain merah solid yang dipadukan dengan logo 3ON pada bagian depan. Bentuk brim yang lebar memberikan perlindungan optimal dari sinar matahari, membantu menjaga fokus selama permainan tanpa mengganggu pandangan.</p>
<p>Terbuat dari material ringan yang mudah menyerap keringat, visor ini menjaga kenyamanan di bawah terik matahari sekaligus memungkinkan aliran udara tetap maksimal karena tidak menutup bagian atas kepala. Strap belakang biasanya dapat disesuaikan, sehingga pas untuk berbagai ukuran kepala dan tetap stabil meski digunakan saat bergerak cepat di lapangan.</p>',
                'url_key' => 'padel-hat-red',
                'new' => 1,
                'featured' => 1,
                'status' => 1,
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'price' => '100000.0000',
                'special_price' => NULL,
                'special_price_from' => NULL,
                'special_price_to' => NULL,
                'weight' => '150.0000',
                'created_at' => '2025-12-03 15:48:13',
                'locale' => 'en',
                'channel' => 'default',
                'attribute_family_id' => 1,
                'product_id' => 63,
                'updated_at' => '2025-12-03 15:51:42',
                'parent_id' => NULL,
                'visible_individually' => 1,
            ),
            10 => 
            array (
                'id' => 64,
                'sku' => 'padel-hat-01-white',
                'type' => 'simple',
                'product_number' => '',
                'name' => 'Padel Hat White',
                'short_description' => '<p>Visor padel berwarna putih dengan logo 3ON pada bagian depan. Ringan, nyaman, dan dirancang untuk melindungi wajah dari sinar matahari tanpa menghalangi sirkulasi udara.</p>',
                'description' => '<p>Visor padel ini menghadirkan tampilan bersih dan modern melalui desain putih solid yang dipadukan dengan logo 3ON pada bagian depan. Bentuk brim yang lebar memberikan perlindungan optimal dari sinar matahari, membantu menjaga fokus selama permainan tanpa mengganggu pandangan.</p>
<p>Terbuat dari material ringan yang mudah menyerap keringat, visor ini menjaga kenyamanan di bawah terik matahari sekaligus memungkinkan aliran udara tetap maksimal karena tidak menutup bagian atas kepala. Strap belakang biasanya dapat disesuaikan, sehingga pas untuk berbagai ukuran kepala dan tetap stabil meski digunakan saat bergerak cepat di lapangan.</p>',
                'url_key' => 'padel-hat-01-white',
                'new' => 1,
                'featured' => 1,
                'status' => 1,
                'meta_title' => '',
                'meta_keywords' => '',
                'meta_description' => '',
                'price' => '100000.0000',
                'special_price' => NULL,
                'special_price_from' => NULL,
                'special_price_to' => NULL,
                'weight' => '150.0000',
                'created_at' => '2025-12-03 15:48:13',
                'locale' => 'en',
                'channel' => 'default',
                'attribute_family_id' => 1,
                'product_id' => 64,
                'updated_at' => '2025-12-03 15:51:42',
                'parent_id' => NULL,
                'visible_individually' => 1,
            ),
        ));
        
        
    }
}