version: "3.8"
services:
  
  #PHP Service
  bagistostore:
    build:
      context: .
      dockerfile: Dockerfile
    image: bagistostore/php
    container_name: bagistostore
    restart: unless-stopped
    tty: true
    ports:
      - "3000:8000"
    volumes:
       - ./:/var/www
       - ./php/local.ini:/usr/local/etc/php/php.ini
       - /var/www/html/vendor
    networks:
      - app-network

  #Nginx Service
  # webserverbagistostore:
  #   image: nginx:alpine
  #   container_name: webserverbagistostore
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "3000:80"
  #   volumes:
  #     - ./:/var/www
  #     - ./nginx/conf.d/:/etc/nginx/conf.d/
  #   networks:
  #     - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge